---
name: Docker Image CI

on:
  push:
    branches: master

jobs:
  build:

    name: Build '${{ matrix.architecture }}' image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture:
          - amd64
          - arm32v7
        include:
          - architecture: amd64
            dockerfile: Dockerfile
          - architecture: arm32v7
            dockerfile: Dockerfile.arm32v7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to DockerHub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and publish image
        uses: ./.github/actions/docker-build-image
        with:
          dockerfile: ${{ matrix.dockerfile }}
          architecture: ${{ matrix.architecture }}

  publish:

    name: Publish multiarch manifest
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to DockerHub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Create and publish manifest list
        uses: ./.github/actions/docker-create-manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        with:
          multiarch: '["amd64", "arm32v7"]'
